export const suggestions = [
    {id: 1, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 2, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 3, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 4, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 5, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 6, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 7, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 8, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 9, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 10, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 11, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 12, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 13, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 14, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 15, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 16, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 17, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 18, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 19, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
    {id: 10, primary: 'MERCADO NA REDE LTDA.', secondary: 'DF - Mercado na Rede Ltda.'},
];